create table if not exists app_users (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    email varchar(255) not null unique,
    role varchar(255) not null check (role in ('ADMIN','SALES','INVENTORY_MANAGER','COORDINATOR','CUSTOMER')),
    password_hash varchar(255) not null,
    active boolean not null default true,
    created_at timestamp with time zone not null default now()
);

create unique index if not exists idx_app_users_email on app_users (email);

create table if not exists books (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    author varchar(255) not null,
    isbn varchar(255) not null unique,
    category varchar(255) not null,
    price numeric(12,2) not null,
    stock_quantity integer not null,
    reorder_level integer not null,
    cover_image_url text,
    active boolean not null default true,
    created_at timestamp with time zone not null default now()
);

create unique index if not exists idx_books_isbn on books (isbn);
create index if not exists idx_books_title on books (title);

create table if not exists customers (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    type varchar(255) not null check (type in ('INDIVIDUAL','CHURCH','SCHOOL','BRANCH')),
    email varchar(255),
    phone varchar(255),
    district varchar(255),
    active boolean not null default true,
    created_at timestamp with time zone not null default now()
);

create table if not exists sales (
    id bigint generated by default as identity primary key,
    customer_id bigint references customers(id),
    cashier_id bigint references app_users(id),
    status varchar(255) not null check (status in ('PAID','HELD','CANCELLED')),
    subtotal numeric(12,2) not null,
    tax numeric(12,2) not null,
    discount numeric(12,2) not null,
    total numeric(12,2) not null,
    created_at timestamp with time zone not null default now()
);

create table if not exists sale_items (
    id bigint generated by default as identity primary key,
    sale_id bigint not null references sales(id),
    book_id bigint not null references books(id),
    quantity integer not null,
    unit_price numeric(12,2) not null,
    line_total numeric(12,2) not null
);

create table if not exists stock_adjustments (
    id bigint generated by default as identity primary key,
    book_id bigint not null references books(id),
    adjusted_by_id bigint references app_users(id),
    type varchar(255) not null check (type in ('RECEIVE_SHIPMENT','CORRECTION','RETURN','DAMAGE','REPRINT_RECEIVED')),
    quantity_delta integer not null,
    note varchar(255),
    created_at timestamp with time zone not null default now()
);

create table if not exists auth_tokens (
    id bigint generated by default as identity primary key,
    token varchar(96) not null unique,
    user_id bigint not null references app_users(id),
    created_at timestamp with time zone not null default now(),
    expires_at timestamp with time zone not null
);

create table if not exists access_requests (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    email varchar(255) not null,
    phone varchar(255),
    department varchar(255),
    requested_role varchar(255) not null check (requested_role in ('ADMIN','SALES','INVENTORY_MANAGER','COORDINATOR','CUSTOMER')),
    status varchar(255) not null check (status in ('PENDING','APPROVED','REJECTED')),
    password_hash varchar(255) not null,
    created_at timestamp with time zone not null default now()
);

create index if not exists idx_access_requests_email on access_requests (email);

create table if not exists production_orders (
    id bigint generated by default as identity primary key,
    book_id bigint not null references books(id),
    created_by_id bigint references app_users(id),
    quantity integer not null,
    printer varchar(255) not null,
    expected_delivery_date date,
    notes varchar(500),
    status varchar(255) not null check (status in ('PLANNED','APPROVED','IN_PROGRESS','RECEIVED','CANCELLED')),
    estimated_cost numeric(12,2) not null,
    created_at timestamp with time zone not null default now()
);
