alter table sales drop constraint if exists sales_status_check;
alter table sales add constraint sales_status_check check (status in ('PENDING','APPROVED','PROCESSING','SHIPPED','DELIVERED','REJECTED','PAID','HELD','CANCELLED'));
alter table sales add column if not exists customer_note varchar(500);
alter table sales add column if not exists internal_note varchar(500);
alter table sales add column if not exists hidden_by_customer boolean not null default false;
alter table sales add column if not exists updated_at timestamp with time zone not null default now();

create table if not exists notifications (
    id bigint generated by default as identity primary key,
    customer_id bigint references customers(id),
    title varchar(255) not null,
    message varchar(700) not null,
    read boolean not null default false,
    created_at timestamp with time zone not null default now()
);

create table if not exists book_requests (
    id bigint generated by default as identity primary key,
    book_id bigint not null references books(id),
    customer_id bigint not null references customers(id),
    quantity integer not null,
    comment varchar(500),
    status varchar(255) not null check (status in ('OPEN','FULFILLED','CANCELLED')),
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);
