create table if not exists audit_logs (
    id bigint generated by default as identity primary key,
    actor_id bigint references app_users(id),
    actor_name varchar(255) not null,
    action varchar(255) not null,
    resource_type varchar(255) not null,
    resource_id bigint,
    summary varchar(700) not null,
    created_at timestamp with time zone not null default now()
);

create index if not exists idx_audit_logs_created_at on audit_logs (created_at);
create index if not exists idx_audit_logs_resource on audit_logs (resource_type, resource_id);
