alter table app_users add column if not exists password_change_required boolean not null default false;

create table if not exists auth_challenges (
    id bigint generated by default as identity primary key,
    challenge_id varchar(64) not null unique,
    user_id bigint not null references app_users(id),
    otp_code varchar(12) not null,
    created_at timestamp with time zone not null default now(),
    expires_at timestamp with time zone not null
);

create unique index if not exists idx_auth_challenges_challenge_id on auth_challenges(challenge_id);
create index if not exists idx_auth_challenges_user on auth_challenges(user_id);
